[uwsgi]
protocol = https
socket = 0.0.0.0:9090
https = =0,ssl/uwsgi_cert.pem,ssl/uwsgi_key.pem,HIGH,!ssl/uwsgi_ca.crt
module = _wsgi:app
master = true
processes = 1
vacuum = true
die-on-term = true
logto = /tmp/%n.log
pidfile = /tmp/%n.pid
callable = app
